// packages/solid-ui/src/internal/form-field.tsx
import type { Theme } from "@better-auth/ui-core";
import type { JSX } from "solid-js";
import { Show } from "solid-js";

interface FormFieldProps {
	label: string;
	error?: string | undefined;
	theme: Theme;
	inputProps: JSX.InputHTMLAttributes<HTMLInputElement>;
}

export function FormField(props: FormFieldProps) {
	const id = () => props.inputProps.id ?? props.inputProps.name;
	return (
		<div class={props.theme.formField}>
			<label for={id() as string} class={props.theme.label}>
				{props.label}
			</label>
			<input
				{...props.inputProps}
				id={id() as string}
				class={props.theme.input}
			/>
			<Show when={props.error}>
				<p class={props.theme.error}>{props.error}</p>
			</Show>
		</div>
	);
}

// packages/react-ui/src/internal/form-field.tsx
import type { Theme } from "@better-auth/ui-core";
import type { InputHTMLAttributes } from "react";

interface FormFieldProps {
	label: string;
	error?: string | undefined;
	theme: Theme;
	inputProps: InputHTMLAttributes<HTMLInputElement>;
}

export function FormField({ label, error, theme, inputProps }: FormFieldProps) {
	const id = inputProps.id ?? inputProps.name;
	return (
		<div className={theme.formField}>
			<label htmlFor={id} className={theme.label}>
				{label}
			</label>
			<input {...inputProps} id={id} className={theme.input} />
			{error && <p className={theme.error}>{error}</p>}
		</div>
	);
}
