// packages/solid-ui/src/internal/social-buttons.tsx
import type { Theme } from "@better-auth/ui-core";
import { getProvidersMeta } from "@better-auth/ui-core";
import { For, Show } from "solid-js";

interface SocialButtonsProps {
	providers: string[];
	theme: Theme;
	redirectUrl?: string | undefined;
	onError?: ((error: unknown) => void) | undefined;
	client: Record<string, unknown>;
}

export function SocialButtons(props: SocialButtonsProps) {
	const meta = () => getProvidersMeta(props.providers);

	const handleSocialSignIn = async (providerId: string) => {
		try {
			const signIn = props.client.signIn as Record<string, unknown>;
			const socialFn = signIn?.social as
				| ((args: Record<string, unknown>) => Promise<unknown>)
				| undefined;
			if (!socialFn) {
				console.error(
					"[better-auth/solid-ui] client.signIn.social is not available.",
				);
				return;
			}
			const body: Record<string, unknown> = { provider: providerId };
			if (props.redirectUrl) body.callbackURL = props.redirectUrl;
			await socialFn(body);
		} catch (err) {
			props.onError?.(err);
		}
	};

	return (
		<Show when={meta().length > 0}>
			<div class={props.theme.socialButtonsContainer}>
				<For each={meta()}>
					{(provider) => (
						<button
							type="button"
							class={props.theme.button.social}
							onClick={() => handleSocialSignIn(provider.id)}
						>
							<span
								innerHTML={provider.icon}
								style={{
									width: "20px",
									height: "20px",
									display: "inline-flex",
								}}
								aria-hidden="true"
							/>
							{provider.name}
						</button>
					)}
				</For>
			</div>
		</Show>
	);
}

// packages/react-ui/src/internal/social-buttons.tsx
import type { Theme } from "@better-auth/ui-core";
import { getProvidersMeta } from "@better-auth/ui-core";
import { useCallback } from "react";

interface SocialButtonsProps {
	providers: string[];
	theme: Theme;
	redirectUrl?: string | undefined;
	onError?: ((error: unknown) => void) | undefined;
	client: Record<string, unknown>;
}

export function SocialButtons({
	providers,
	theme,
	redirectUrl,
	onError,
	client,
}: SocialButtonsProps) {
	const meta = getProvidersMeta(providers);

	const handleSocialSignIn = useCallback(
		async (providerId: string) => {
			try {
				const signIn = client.signIn as Record<string, unknown>;
				const socialFn = signIn?.social as
					| ((args: Record<string, unknown>) => Promise<unknown>)
					| undefined;
				if (!socialFn) {
					console.error(
						"[better-auth/react-ui] client.signIn.social is not available.",
					);
					return;
				}
				const body: Record<string, unknown> = { provider: providerId };
				if (redirectUrl) body.callbackURL = redirectUrl;
				await socialFn(body);
			} catch (err) {
				onError?.(err);
			}
		},
		[client, redirectUrl, onError],
	);

	if (meta.length === 0) return null;

	return (
		<div className={theme.socialButtonsContainer}>
			{meta.map((provider) => (
				<button
					key={provider.id}
					type="button"
					className={theme.button.social}
					onClick={() => handleSocialSignIn(provider.id)}
				>
					<span
						dangerouslySetInnerHTML={{ __html: provider.icon }}
						style={{ width: 20, height: 20, display: "inline-flex" }}
						aria-hidden="true"
					/>
					{provider.name}
				</button>
			))}
		</div>
	);
}
